# Generated by Django 2.2.4 on 2019-08-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190807_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samosval',
            name='nomer',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
