# Generated by Django 2.2.4 on 2019-08-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190807_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='samosval',
            name='pjdemnost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='samosval',
            name='zagrujennost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='samosval',
            name='model',
            field=models.CharField(choices=[(1, 'Белаз'), (2, 'Kamatsu')], max_length=150),
        ),
    ]
