# Generated by Django 2.2.4 on 2019-08-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190807_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='samosval',
            name='zapolnen',
            field=models.IntegerField(default=1),
        ),
    ]
