# Generated by Django 2.2.4 on 2019-08-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_samosval_zapolnen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samosval',
            name='pjdemnost',
            field=models.IntegerField(),
        ),
    ]
