# Generated by Django 2.2.4 on 2019-08-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190807_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samosval',
            name='model',
            field=models.CharField(choices=[('Белаз', 'Белаз'), ('Kamatsu', 'Kamatsu')], max_length=150),
        ),
    ]
