# Generated by Django 2.2.4 on 2019-08-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190807_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samosval',
            name='zagrujennost',
            field=models.IntegerField(),
        ),
    ]
