# Generated by Django 2.2.4 on 2019-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_samosval_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samosval',
            name='zagrujennost',
            field=models.IntegerField(db_index=True, default=120),
        ),
    ]
