# Generated by Django 2.2.4 on 2019-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190807_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samosval',
            old_name='pjdemnost',
            new_name='podemnost',
        ),
        migrations.AlterField(
            model_name='samosval',
            name='in_stock',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
