# Generated by Django 2.2.4 on 2019-08-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190807_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samosval',
            name='in_stock',
        ),
    ]
